//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysColumnFilter
    {
    	
    	  public SysColumnFilter()
        {
    
    			//------------------------------------------------------------------------------
                // <auto-generated>
                //     此代码已从模板生成。  create by chand 2016-04-13
                //
                //     手动更改此文件可能导致应用程序出现意外的行为。
                //     如果重新生成代码，将覆盖对此文件的手动更改。
                // </auto-generated>
                //------------------------------------------------------------------------------
    			this.SysMenuID = String.Empty;
    				this.SysPersonID = String.Empty;
    				this.ColumnName = String.Empty;
    				this.ColumnText = String.Empty;
    				this.Sort =0;
    				this.ColumnWidth =0;
    				this.IsShow =false;
    				this.IsCondition =false;
    				this.IsDelete =false;
    				this.VersionNo =0;
    				this.CreatedBy = String.Empty;
    				this.CreatedTime = DateTime.Now;
    				this.LastUpdatedBy = String.Empty;
    				this.LastUpdatedTime = DateTime.Now;
    		
    
    
    	}
    	    public string SysMenuID { get; set; }
        public string SysPersonID { get; set; }
        public string ColumnName { get; set; }
        public string ColumnText { get; set; }
        public int Sort { get; set; }
        public int ColumnWidth { get; set; }
        public bool IsShow { get; set; }
        public bool IsCondition { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<int> VersionNo { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
