//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Contract
    {
    	
    	  public TB_Contract()
        {
    
    			//------------------------------------------------------------------------------
                // <auto-generated>
                //     此代码已从模板生成。  create by chand 2016-04-13
                //
                //     手动更改此文件可能导致应用程序出现意外的行为。
                //     如果重新生成代码，将覆盖对此文件的手动更改。
                // </auto-generated>
                //------------------------------------------------------------------------------
    			this.ContractID = String.Empty;
    				this.CustomerID = String.Empty;
    				this.CustomerName = String.Empty;
    				this.ContractMoney = String.Empty;
    				this.Package = String.Empty;
    				this.Annex = String.Empty;
    				this.Years = String.Empty;
    				this.ContractCount =0;
    				this.IsDelete =false;
    				this.VersionNo =0;
    				this.CreatedBy = String.Empty;
    				this.CreatedTime = DateTime.Now;
    				this.LastUpdatedBy = String.Empty;
    				this.LastUpdatedTime = DateTime.Now;
    				this.ContractNO = String.Empty;
    				this.SigningCompany = String.Empty;
    				this.Flag =0;
    				this.PhoneNumber = String.Empty;
    				this.ProjectLeader = String.Empty;
    				this.ContractType = String.Empty;
    				this.ContractName = String.Empty;
    				this.IsNew =0;
    				this.PayType = String.Empty;
    				this.Remark = String.Empty;
    		
    
    
    	}
    	    public string ContractID { get; set; }
        public string CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string ContractMoney { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public System.DateTime Deadline { get; set; }
        public string Package { get; set; }
        public string Annex { get; set; }
        public string Years { get; set; }
        public Nullable<int> ContractCount { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> VersionNo { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
        public string ContractNO { get; set; }
        public string SigningCompany { get; set; }
        public Nullable<int> Flag { get; set; }
        public string PhoneNumber { get; set; }
        public string ProjectLeader { get; set; }
        public string ContractType { get; set; }
        public string ContractName { get; set; }
        public Nullable<int> IsNew { get; set; }
        public string PayType { get; set; }
        public string Remark { get; set; }
    }
}
