//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CustomerRating
    {
    	
    	  public TB_CustomerRating()
        {
    
    			//------------------------------------------------------------------------------
                // <auto-generated>
                //     此代码已从模板生成。  create by chand 2016-04-13
                //
                //     手动更改此文件可能导致应用程序出现意外的行为。
                //     如果重新生成代码，将覆盖对此文件的手动更改。
                // </auto-generated>
                //------------------------------------------------------------------------------
    			this.CustomerRatingID = String.Empty;
    				this.CustomerID = String.Empty;
    				this.CompanyNatureCode = String.Empty;
    				this.RegisterCapital = String.Empty;
    				this.SalesRevenue = String.Empty;
    				this.ContractPeriod = String.Empty;
    				this.OverdueAdvances = String.Empty;
    				this.RatingScore = String.Empty;
    				this.IsDelete =false;
    				this.VersionNo =0;
    				this.CreatedBy = String.Empty;
    				this.CreatedTime = DateTime.Now;
    				this.LastUpdatedBy = String.Empty;
    				this.LastUpdatedTime = DateTime.Now;
    		
    
    
    	}
    	    public string CustomerRatingID { get; set; }
        public string CustomerID { get; set; }
        public string CompanyNatureCode { get; set; }
        public string RegisterCapital { get; set; }
        public string SalesRevenue { get; set; }
        public string ContractPeriod { get; set; }
        public string OverdueAdvances { get; set; }
        public string RatingScore { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> VersionNo { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
