//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CompanyInterviewJob
    {
    	
    	  public TB_CompanyInterviewJob()
        {
    
    			//------------------------------------------------------------------------------
                // <auto-generated>
                //     此代码已从模板生成。  create by chand 2016-04-13
                //
                //     手动更改此文件可能导致应用程序出现意外的行为。
                //     如果重新生成代码，将覆盖对此文件的手动更改。
                // </auto-generated>
                //------------------------------------------------------------------------------
    			this.CompanyInterviewJobID =0;
    				this.CompanyID =0;
    				this.AddressID =0;
    				this.CityCode = String.Empty;
    				this.WorkAddress = String.Empty;
    				this.JobTitle = String.Empty;
    				this.JobTypeCode = String.Empty;
    				this.SalaryCode = String.Empty;
    				this.OnlineInterviewTypeCode = String.Empty;
    				this.PositionTypeCode = String.Empty;
    				this.EducationCode = String.Empty;
    				this.Capacity =0;
    				this.WorkExperenceCode = String.Empty;
    				this.ManageExperenceCode = String.Empty;
    				this.AgeFrom =0;
    				this.AgeTo =0;
    				this.DomainCode = String.Empty;
    				this.SubdomainCode = String.Empty;
    				this.JobResponsibility = String.Empty;
    				this.PositionRequirement = String.Empty;
    				this.InterviewTypeCode = String.Empty;
    				this.AllowCode = String.Empty;
    				this.IsResumeRequired =false;
    				this.IsOpusRequired =false;
    				this.IsCertificationRequired =false;
    				this.QuestionnaireID =0;
    				this.InterviewLink = String.Empty;
    				this.ExpireDate = DateTime.Now;
    				this.InterviewDate = DateTime.Now;
    				this.JobStatusCode = String.Empty;
    				this.VersionNo =0;
    				this.TransactionID = String.Empty;
    				this.CreatedBy = String.Empty;
    				this.LastUpdatedBy = String.Empty;
    				this.IsJobFaire =false;
    				this.JobCheckStatusCode = String.Empty;
    				this.CheckedBy = String.Empty;
    				this.CheckedTime = DateTime.Now;
    				this.CheckNoPassReason = String.Empty;
    				this.JobFaireState =0;
    				this.Email = String.Empty;
    				this.IsUrgent =false;
    				this.Gender = String.Empty;
    				this.Department = String.Empty;
    				this.Age = String.Empty;
    				this.VocationCode = String.Empty;
    		
    
    
    	}
    	    public int CompanyInterviewJobID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> AddressID { get; set; }
        public string CityCode { get; set; }
        public string WorkAddress { get; set; }
        public string JobTitle { get; set; }
        public string JobTypeCode { get; set; }
        public string SalaryCode { get; set; }
        public string OnlineInterviewTypeCode { get; set; }
        public string PositionTypeCode { get; set; }
        public string EducationCode { get; set; }
        public Nullable<int> Capacity { get; set; }
        public string WorkExperenceCode { get; set; }
        public string ManageExperenceCode { get; set; }
        public Nullable<int> AgeFrom { get; set; }
        public Nullable<int> AgeTo { get; set; }
        public string DomainCode { get; set; }
        public string SubdomainCode { get; set; }
        public string JobResponsibility { get; set; }
        public string PositionRequirement { get; set; }
        public string InterviewTypeCode { get; set; }
        public string AllowCode { get; set; }
        public Nullable<bool> IsResumeRequired { get; set; }
        public Nullable<bool> IsOpusRequired { get; set; }
        public Nullable<bool> IsCertificationRequired { get; set; }
        public int QuestionnaireID { get; set; }
        public string InterviewLink { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<System.DateTime> InterviewDate { get; set; }
        public string JobStatusCode { get; set; }
        public int VersionNo { get; set; }
        public string TransactionID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string LastUpdatedBy { get; set; }
        public System.DateTime LastUpdatedTime { get; set; }
        public Nullable<bool> IsJobFaire { get; set; }
        public string JobCheckStatusCode { get; set; }
        public string CheckedBy { get; set; }
        public Nullable<System.DateTime> CheckedTime { get; set; }
        public string CheckNoPassReason { get; set; }
        public Nullable<int> JobFaireState { get; set; }
        public string Email { get; set; }
        public Nullable<bool> IsUrgent { get; set; }
        public string Gender { get; set; }
        public string Department { get; set; }
        public string Age { get; set; }
        public string VocationCode { get; set; }
        public Nullable<short> JobLevel { get; set; }
    }
}
