//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CustomerFollow
    {
    	
    	  public TB_CustomerFollow()
        {
    
    			//------------------------------------------------------------------------------
                // <auto-generated>
                //     此代码已从模板生成。  create by chand 2016-04-13
                //
                //     手动更改此文件可能导致应用程序出现意外的行为。
                //     如果重新生成代码，将覆盖对此文件的手动更改。
                // </auto-generated>
                //------------------------------------------------------------------------------
    			this.CustomerFollowID = String.Empty;
    				this.CustomerID = String.Empty;
    				this.FollowUpMode = String.Empty;
    				this.FollowUpCategory = String.Empty;
    				this.OtherLevel = String.Empty;
    				this.FollowUpPurpose = String.Empty;
    				this.ProvinceCode = String.Empty;
    				this.ProvinceName = String.Empty;
    				this.CityCode = String.Empty;
    				this.CityName = String.Empty;
    				this.DistrictCode = String.Empty;
    				this.DistrictName = String.Empty;
    				this.AddressDetails = String.Empty;
    				this.FollowUpDate = DateTime.Now;
    				this.CustomerContactName = String.Empty;
    				this.CallPhone = String.Empty;
    				this.CustomerFeedback = String.Empty;
    				this.CustomerFunnel = String.Empty;
    				this.ProcessMode = String.Empty;
    				this.Opportunities = String.Empty;
    				this.ExpectedMoney = String.Empty;
    				this.ExpectedDate = DateTime.Now;
    				this.NextFollowDate = DateTime.Now;
    				this.NextFollowUpMode = String.Empty;
    				this.Remark = String.Empty;
    				this.FileUrl = String.Empty;
    				this.SysPersonID = String.Empty;
    				this.IsFinish =false;
    				this.VersionNo =0;
    				this.IsDelete =false;
    				this.CreatedTime = DateTime.Now;
    				this.CreatedBy = String.Empty;
    				this.LastUpdatedTime = DateTime.Now;
    				this.LastUpdatedBy = String.Empty;
    				this.FollowType =0;
    				this.IsKP =false;
    				this.GoTime = DateTime.Now;
    				this.BackTime = DateTime.Now;
    		
    
    
    	}
    	    public string CustomerFollowID { get; set; }
        public string CustomerID { get; set; }
        public System.DateTime ReservationDate { get; set; }
        public string FollowUpMode { get; set; }
        public string FollowUpCategory { get; set; }
        public string OtherLevel { get; set; }
        public string FollowUpPurpose { get; set; }
        public string ProvinceCode { get; set; }
        public string ProvinceName { get; set; }
        public string CityCode { get; set; }
        public string CityName { get; set; }
        public string DistrictCode { get; set; }
        public string DistrictName { get; set; }
        public string AddressDetails { get; set; }
        public short ContactState { get; set; }
        public Nullable<System.DateTime> FollowUpDate { get; set; }
        public string CustomerContactName { get; set; }
        public string CallPhone { get; set; }
        public string CustomerFeedback { get; set; }
        public string CustomerFunnel { get; set; }
        public string ProcessMode { get; set; }
        public string Opportunities { get; set; }
        public string ExpectedMoney { get; set; }
        public Nullable<System.DateTime> ExpectedDate { get; set; }
        public Nullable<System.DateTime> NextFollowDate { get; set; }
        public string NextFollowUpMode { get; set; }
        public string Remark { get; set; }
        public string FileUrl { get; set; }
        public string SysPersonID { get; set; }
        public Nullable<bool> IsFinish { get; set; }
        public Nullable<int> VersionNo { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<int> FollowType { get; set; }
        public Nullable<bool> IsKP { get; set; }
        public Nullable<System.DateTime> GoTime { get; set; }
        public Nullable<System.DateTime> BackTime { get; set; }
    }
}
