//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CallLog
    {
    	
    	  public TB_CallLog()
        {
    
    			//------------------------------------------------------------------------------
                // <auto-generated>
                //     此代码已从模板生成。  create by chand 2016-04-13
                //
                //     手动更改此文件可能导致应用程序出现意外的行为。
                //     如果重新生成代码，将覆盖对此文件的手动更改。
                // </auto-generated>
                //------------------------------------------------------------------------------
    			this.CallLogID = String.Empty;
    				this.SysPersonID = String.Empty;
    				this.CustomerID = String.Empty;
    				this.CustomerContactID = String.Empty;
    				this.ToTel = String.Empty;
    				this.ToExten = String.Empty;
    				this.IsConnected =false;
    				this.TalkTimeLength =0;
    				this.IsDelete =false;
    				this.VersionNo =0;
    				this.CreatedBy = String.Empty;
    				this.CreatedTime = DateTime.Now;
    				this.LastUpdatedBy = String.Empty;
    				this.LastUpdatedTime = DateTime.Now;
    		
    
    
    	}
    	    public string CallLogID { get; set; }
        public string SysPersonID { get; set; }
        public string CustomerID { get; set; }
        public string CustomerContactID { get; set; }
        public string ToTel { get; set; }
        public string ToExten { get; set; }
        public Nullable<bool> IsConnected { get; set; }
        public Nullable<int> TalkTimeLength { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> VersionNo { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    
        public virtual SysPerson SysPerson { get; set; }
        public virtual TB_Customer TB_Customer { get; set; }
    }
}
