//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SoundComment
    {
    	
    	  public TB_SoundComment()
        {
    
    			//------------------------------------------------------------------------------
                // <auto-generated>
                //     此代码已从模板生成。  create by chand 2016-04-13
                //
                //     手动更改此文件可能导致应用程序出现意外的行为。
                //     如果重新生成代码，将覆盖对此文件的手动更改。
                // </auto-generated>
                //------------------------------------------------------------------------------
    			this.CommentID = String.Empty;
    				this.TelCode =0;
    				this.SoundID = String.Empty;
    				this.SoundURL = String.Empty;
    				this.SoundType = String.Empty;
    				this.SoundGoodRemark = String.Empty;
    				this.SoundBadRemark = String.Empty;
    				this.SoundImproveRemark = String.Empty;
    				this.CreateUserID = String.Empty;
    				this.UpdateUserID = String.Empty;
    		
    
    
    	}
    	    public string CommentID { get; set; }
        public int TelCode { get; set; }
        public string SoundID { get; set; }
        public string SoundURL { get; set; }
        public string SoundType { get; set; }
        public string SoundGoodRemark { get; set; }
        public string SoundBadRemark { get; set; }
        public string SoundImproveRemark { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreateUserID { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public string UpdateUserID { get; set; }
    }
}
