//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SalesPerformance
    {
    	
    	  public TB_SalesPerformance()
        {
    
    			//------------------------------------------------------------------------------
                // <auto-generated>
                //     此代码已从模板生成。  create by chand 2016-04-13
                //
                //     手动更改此文件可能导致应用程序出现意外的行为。
                //     如果重新生成代码，将覆盖对此文件的手动更改。
                // </auto-generated>
                //------------------------------------------------------------------------------
    			this.SalesPerformanceID = String.Empty;
    				this.SysPersonID = String.Empty;
    				this.TheMonth = String.Empty;
    				this.TheWeek =0;
    				this.IntervalName = String.Empty;
    				this.FollowUpQty =0;
    				this.ContractQty =0;
    				this.BillingAmount =0;
    				this.KeyCustomerQty =0;
    				this.FollowUpAvg =0;
    				this.IsDelete =false;
    				this.VersionNo =0;
    				this.CreatedBy = String.Empty;
    				this.CreatedTime = DateTime.Now;
    				this.LastUpdatedBy = String.Empty;
    				this.LastUpdatedTime = DateTime.Now;
    				this.BudgetAmount =0;
    		
    
    
    	}
    	    public string SalesPerformanceID { get; set; }
        public string SysPersonID { get; set; }
        public string TheMonth { get; set; }
        public Nullable<int> TheWeek { get; set; }
        public string IntervalName { get; set; }
        public Nullable<short> Category { get; set; }
        public Nullable<int> FollowUpQty { get; set; }
        public Nullable<int> ContractQty { get; set; }
        public Nullable<decimal> BillingAmount { get; set; }
        public Nullable<int> KeyCustomerQty { get; set; }
        public Nullable<decimal> FollowUpAvg { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> VersionNo { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
        public Nullable<decimal> BudgetAmount { get; set; }
    }
}
