//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TP_SalaryItem
    {
    	
    	  public TP_SalaryItem()
        {
    
    			//------------------------------------------------------------------------------
                // <auto-generated>
                //     此代码已从模板生成。  create by chand 2016-04-13
                //
                //     手动更改此文件可能导致应用程序出现意外的行为。
                //     如果重新生成代码，将覆盖对此文件的手动更改。
                // </auto-generated>
                //------------------------------------------------------------------------------
    			this.SalaryItemID = String.Empty;
    				this.ItemCode = String.Empty;
    				this.ItemName = String.Empty;
    				this.DataType =0;
    				this.ItemClass =0;
    				this.Sort =0;
    				this.IsDel =false;
    		
    
    
    	}
    	    public string SalaryItemID { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> DataType { get; set; }
        public Nullable<int> ItemClass { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<bool> IsDel { get; set; }
    }
}
