//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TP_SocialInsur
    {
    	
    	  public TP_SocialInsur()
        {
    
    			//------------------------------------------------------------------------------
                // <auto-generated>
                //     此代码已从模板生成。  create by chand 2016-04-13
                //
                //     手动更改此文件可能导致应用程序出现意外的行为。
                //     如果重新生成代码，将覆盖对此文件的手动更改。
                // </auto-generated>
                //------------------------------------------------------------------------------
    			this.SocialInsurID = String.Empty;
    				this.SocialInsurName = String.Empty;
    				this.ProvinceCode = String.Empty;
    				this.CityCode = String.Empty;
    				this.DistrictCode = String.Empty;
    				this.DiffBegin =0;
    				this.DiffEnd =0;
    				this.IndiPension =0;
    				this.CompanyPension =0;
    				this.IndiInjury =0;
    				this.CompanyInjury =0;
    				this.IndiMedical =0;
    				this.CompanyMedical =0;
    				this.IndiBirth =0;
    				this.CompanyBirth =0;
    				this.IndiSupply =0;
    				this.CompanySupply =0;
    				this.IndiDBTC =0;
    				this.CompanyDBTC =0;
    				this.IsDelete =false;
    				this.VersionNo =0;
    				this.CreatedBy = String.Empty;
    				this.CreatedTime = DateTime.Now;
    				this.LastUpdatedBy = String.Empty;
    				this.LastUpdatedTime = DateTime.Now;
    		
    
    
    	}
    	    public string SocialInsurID { get; set; }
        public string SocialInsurName { get; set; }
        public string ProvinceCode { get; set; }
        public string CityCode { get; set; }
        public string DistrictCode { get; set; }
        public Nullable<decimal> DiffBegin { get; set; }
        public Nullable<decimal> DiffEnd { get; set; }
        public Nullable<decimal> IndiPension { get; set; }
        public Nullable<decimal> CompanyPension { get; set; }
        public Nullable<decimal> IndiInjury { get; set; }
        public Nullable<decimal> CompanyInjury { get; set; }
        public Nullable<decimal> IndiMedical { get; set; }
        public Nullable<decimal> CompanyMedical { get; set; }
        public Nullable<decimal> IndiBirth { get; set; }
        public Nullable<decimal> CompanyBirth { get; set; }
        public Nullable<decimal> IndiSupply { get; set; }
        public Nullable<decimal> CompanySupply { get; set; }
        public Nullable<decimal> IndiDBTC { get; set; }
        public Nullable<decimal> CompanyDBTC { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> VersionNo { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
