//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.19453
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.App.SendSmsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", ConfigurationName="SendSmsService.SDKClient")]
    public interface SDKClient {
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CRM.App.SendSmsService.getVersionResponse getVersion(CRM.App.SendSmsService.getVersionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CRM.App.SendSmsService.getVersionResponse> getVersionAsync(CRM.App.SendSmsService.getVersionRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CRM.App.SendSmsService.getReportResponse getReport(CRM.App.SendSmsService.getReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CRM.App.SendSmsService.getReportResponse> getReportAsync(CRM.App.SendSmsService.getReportRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CRM.App.SendSmsService.cancelMOForwardResponse cancelMOForward(CRM.App.SendSmsService.cancelMOForwardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CRM.App.SendSmsService.cancelMOForwardResponse> cancelMOForwardAsync(CRM.App.SendSmsService.cancelMOForwardRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CRM.App.SendSmsService.chargeUpResponse chargeUp(CRM.App.SendSmsService.chargeUpRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CRM.App.SendSmsService.chargeUpResponse> chargeUpAsync(CRM.App.SendSmsService.chargeUpRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CRM.App.SendSmsService.getBalanceResponse getBalance(CRM.App.SendSmsService.getBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CRM.App.SendSmsService.getBalanceResponse> getBalanceAsync(CRM.App.SendSmsService.getBalanceRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CRM.App.SendSmsService.getEachFeeResponse getEachFee(CRM.App.SendSmsService.getEachFeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CRM.App.SendSmsService.getEachFeeResponse> getEachFeeAsync(CRM.App.SendSmsService.getEachFeeRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CRM.App.SendSmsService.getMOResponse getMO(CRM.App.SendSmsService.getMORequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CRM.App.SendSmsService.getMOResponse> getMOAsync(CRM.App.SendSmsService.getMORequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CRM.App.SendSmsService.logoutResponse logout(CRM.App.SendSmsService.logoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CRM.App.SendSmsService.logoutResponse> logoutAsync(CRM.App.SendSmsService.logoutRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CRM.App.SendSmsService.registDetailInfoResponse registDetailInfo(CRM.App.SendSmsService.registDetailInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CRM.App.SendSmsService.registDetailInfoResponse> registDetailInfoAsync(CRM.App.SendSmsService.registDetailInfoRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CRM.App.SendSmsService.registExResponse registEx(CRM.App.SendSmsService.registExRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CRM.App.SendSmsService.registExResponse> registExAsync(CRM.App.SendSmsService.registExRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CRM.App.SendSmsService.sendSMSResponse sendSMS(CRM.App.SendSmsService.sendSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CRM.App.SendSmsService.sendSMSResponse> sendSMSAsync(CRM.App.SendSmsService.sendSMSRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CRM.App.SendSmsService.sendVoiceResponse sendVoice(CRM.App.SendSmsService.sendVoiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CRM.App.SendSmsService.sendVoiceResponse> sendVoiceAsync(CRM.App.SendSmsService.sendVoiceRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CRM.App.SendSmsService.serialPwdUpdResponse serialPwdUpd(CRM.App.SendSmsService.serialPwdUpdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CRM.App.SendSmsService.serialPwdUpdResponse> serialPwdUpdAsync(CRM.App.SendSmsService.serialPwdUpdRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CRM.App.SendSmsService.setMOForwardResponse setMOForward(CRM.App.SendSmsService.setMOForwardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CRM.App.SendSmsService.setMOForwardResponse> setMOForwardAsync(CRM.App.SendSmsService.setMOForwardRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CRM.App.SendSmsService.setMOForwardExResponse setMOForwardEx(CRM.App.SendSmsService.setMOForwardExRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CRM.App.SendSmsService.setMOForwardExResponse> setMOForwardExAsync(CRM.App.SendSmsService.setMOForwardExRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getVersion", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class getVersionRequest {
        
        public getVersionRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getVersionResponse", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class getVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getVersionResponse() {
        }
        
        public getVersionResponse(string @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36246")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/")]
    public partial class statusReport : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorCodeField;
        
        private string memoField;
        
        private string mobileField;
        
        private string receiveDateField;
        
        private int reportStatusField;
        
        private long seqIDField;
        
        private string serviceCodeAddField;
        
        private string submitDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string memo {
            get {
                return this.memoField;
            }
            set {
                this.memoField = value;
                this.RaisePropertyChanged("memo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
                this.RaisePropertyChanged("mobile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string receiveDate {
            get {
                return this.receiveDateField;
            }
            set {
                this.receiveDateField = value;
                this.RaisePropertyChanged("receiveDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int reportStatus {
            get {
                return this.reportStatusField;
            }
            set {
                this.reportStatusField = value;
                this.RaisePropertyChanged("reportStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public long seqID {
            get {
                return this.seqIDField;
            }
            set {
                this.seqIDField = value;
                this.RaisePropertyChanged("seqID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string serviceCodeAdd {
            get {
                return this.serviceCodeAddField;
            }
            set {
                this.serviceCodeAddField = value;
                this.RaisePropertyChanged("serviceCodeAdd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string submitDate {
            get {
                return this.submitDateField;
            }
            set {
                this.submitDateField = value;
                this.RaisePropertyChanged("submitDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36246")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/")]
    public partial class mo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string addSerialField;
        
        private string addSerialRevField;
        
        private string channelnumberField;
        
        private string mobileNumberField;
        
        private string sentTimeField;
        
        private string smsContentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string addSerial {
            get {
                return this.addSerialField;
            }
            set {
                this.addSerialField = value;
                this.RaisePropertyChanged("addSerial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string addSerialRev {
            get {
                return this.addSerialRevField;
            }
            set {
                this.addSerialRevField = value;
                this.RaisePropertyChanged("addSerialRev");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string channelnumber {
            get {
                return this.channelnumberField;
            }
            set {
                this.channelnumberField = value;
                this.RaisePropertyChanged("channelnumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string mobileNumber {
            get {
                return this.mobileNumberField;
            }
            set {
                this.mobileNumberField = value;
                this.RaisePropertyChanged("mobileNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string sentTime {
            get {
                return this.sentTimeField;
            }
            set {
                this.sentTimeField = value;
                this.RaisePropertyChanged("sentTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string smsContent {
            get {
                return this.smsContentField;
            }
            set {
                this.smsContentField = value;
                this.RaisePropertyChanged("smsContent");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getReport", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class getReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public getReportRequest() {
        }
        
        public getReportRequest(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getReportResponse", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class getReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CRM.App.SendSmsService.statusReport[] @return;
        
        public getReportResponse() {
        }
        
        public getReportResponse(CRM.App.SendSmsService.statusReport[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelMOForward", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class cancelMOForwardRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public cancelMOForwardRequest() {
        }
        
        public cancelMOForwardRequest(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelMOForwardResponse", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class cancelMOForwardResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public cancelMOForwardResponse() {
        }
        
        public cancelMOForwardResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="chargeUp", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class chargeUpRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg3;
        
        public chargeUpRequest() {
        }
        
        public chargeUpRequest(string arg0, string arg1, string arg2, string arg3) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="chargeUpResponse", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class chargeUpResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public chargeUpResponse() {
        }
        
        public chargeUpResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBalance", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class getBalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public getBalanceRequest() {
        }
        
        public getBalanceRequest(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBalanceResponse", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class getBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double @return;
        
        public getBalanceResponse() {
        }
        
        public getBalanceResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEachFee", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class getEachFeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public getEachFeeRequest() {
        }
        
        public getEachFeeRequest(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEachFeeResponse", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class getEachFeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double @return;
        
        public getEachFeeResponse() {
        }
        
        public getEachFeeResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMO", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class getMORequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public getMORequest() {
        }
        
        public getMORequest(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMOResponse", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class getMOResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CRM.App.SendSmsService.mo[] @return;
        
        public getMOResponse() {
        }
        
        public getMOResponse(CRM.App.SendSmsService.mo[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="logout", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class logoutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public logoutRequest() {
        }
        
        public logoutRequest(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="logoutResponse", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class logoutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public logoutResponse() {
        }
        
        public logoutResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registDetailInfo", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class registDetailInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg6;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg7;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg8;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg9;
        
        public registDetailInfoRequest() {
        }
        
        public registDetailInfoRequest(string arg0, string arg1, string arg2, string arg3, string arg4, string arg5, string arg6, string arg7, string arg8, string arg9) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
            this.arg5 = arg5;
            this.arg6 = arg6;
            this.arg7 = arg7;
            this.arg8 = arg8;
            this.arg9 = arg9;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registDetailInfoResponse", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class registDetailInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public registDetailInfoResponse() {
        }
        
        public registDetailInfoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registEx", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class registExRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        public registExRequest() {
        }
        
        public registExRequest(string arg0, string arg1, string arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registExResponse", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class registExResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public registExResponse() {
        }
        
        public registExResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSMS", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class sendSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("arg3", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] arg3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg6;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg7;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg8;
        
        public sendSMSRequest() {
        }
        
        public sendSMSRequest(string arg0, string arg1, string arg2, string[] arg3, string arg4, string arg5, string arg6, int arg7, long arg8) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
            this.arg5 = arg5;
            this.arg6 = arg6;
            this.arg7 = arg7;
            this.arg8 = arg8;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSMSResponse", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class sendSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public sendSMSResponse() {
        }
        
        public sendSMSResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendVoice", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class sendVoiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("arg3", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] arg3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg6;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg7;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg8;
        
        public sendVoiceRequest() {
        }
        
        public sendVoiceRequest(string arg0, string arg1, string arg2, string[] arg3, string arg4, string arg5, string arg6, int arg7, long arg8) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
            this.arg5 = arg5;
            this.arg6 = arg6;
            this.arg7 = arg7;
            this.arg8 = arg8;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendVoiceResponse", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class sendVoiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public sendVoiceResponse() {
        }
        
        public sendVoiceResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="serialPwdUpd", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class serialPwdUpdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg3;
        
        public serialPwdUpdRequest() {
        }
        
        public serialPwdUpdRequest(string arg0, string arg1, string arg2, string arg3) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="serialPwdUpdResponse", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class serialPwdUpdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public serialPwdUpdResponse() {
        }
        
        public serialPwdUpdResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setMOForward", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class setMOForwardRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        public setMOForwardRequest() {
        }
        
        public setMOForwardRequest(string arg0, string arg1, string arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setMOForwardResponse", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class setMOForwardResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public setMOForwardResponse() {
        }
        
        public setMOForwardResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setMOForwardEx", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class setMOForwardExRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("arg2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] arg2;
        
        public setMOForwardExRequest() {
        }
        
        public setMOForwardExRequest(string arg0, string arg1, string[] arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setMOForwardExResponse", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class setMOForwardExResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public setMOForwardExResponse() {
        }
        
        public setMOForwardExResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SDKClientChannel : CRM.App.SendSmsService.SDKClient, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SDKClientClient : System.ServiceModel.ClientBase<CRM.App.SendSmsService.SDKClient>, CRM.App.SendSmsService.SDKClient {
        
        public SDKClientClient() {
        }
        
        public SDKClientClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SDKClientClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SDKClientClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SDKClientClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRM.App.SendSmsService.getVersionResponse CRM.App.SendSmsService.SDKClient.getVersion(CRM.App.SendSmsService.getVersionRequest request) {
            return base.Channel.getVersion(request);
        }
        
        public string getVersion() {
            CRM.App.SendSmsService.getVersionRequest inValue = new CRM.App.SendSmsService.getVersionRequest();
            CRM.App.SendSmsService.getVersionResponse retVal = ((CRM.App.SendSmsService.SDKClient)(this)).getVersion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CRM.App.SendSmsService.getVersionResponse> CRM.App.SendSmsService.SDKClient.getVersionAsync(CRM.App.SendSmsService.getVersionRequest request) {
            return base.Channel.getVersionAsync(request);
        }
        
        public System.Threading.Tasks.Task<CRM.App.SendSmsService.getVersionResponse> getVersionAsync() {
            CRM.App.SendSmsService.getVersionRequest inValue = new CRM.App.SendSmsService.getVersionRequest();
            return ((CRM.App.SendSmsService.SDKClient)(this)).getVersionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRM.App.SendSmsService.getReportResponse CRM.App.SendSmsService.SDKClient.getReport(CRM.App.SendSmsService.getReportRequest request) {
            return base.Channel.getReport(request);
        }
        
        public CRM.App.SendSmsService.statusReport[] getReport(string arg0, string arg1) {
            CRM.App.SendSmsService.getReportRequest inValue = new CRM.App.SendSmsService.getReportRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            CRM.App.SendSmsService.getReportResponse retVal = ((CRM.App.SendSmsService.SDKClient)(this)).getReport(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CRM.App.SendSmsService.getReportResponse> CRM.App.SendSmsService.SDKClient.getReportAsync(CRM.App.SendSmsService.getReportRequest request) {
            return base.Channel.getReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<CRM.App.SendSmsService.getReportResponse> getReportAsync(string arg0, string arg1) {
            CRM.App.SendSmsService.getReportRequest inValue = new CRM.App.SendSmsService.getReportRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((CRM.App.SendSmsService.SDKClient)(this)).getReportAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRM.App.SendSmsService.cancelMOForwardResponse CRM.App.SendSmsService.SDKClient.cancelMOForward(CRM.App.SendSmsService.cancelMOForwardRequest request) {
            return base.Channel.cancelMOForward(request);
        }
        
        public int cancelMOForward(string arg0, string arg1) {
            CRM.App.SendSmsService.cancelMOForwardRequest inValue = new CRM.App.SendSmsService.cancelMOForwardRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            CRM.App.SendSmsService.cancelMOForwardResponse retVal = ((CRM.App.SendSmsService.SDKClient)(this)).cancelMOForward(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CRM.App.SendSmsService.cancelMOForwardResponse> CRM.App.SendSmsService.SDKClient.cancelMOForwardAsync(CRM.App.SendSmsService.cancelMOForwardRequest request) {
            return base.Channel.cancelMOForwardAsync(request);
        }
        
        public System.Threading.Tasks.Task<CRM.App.SendSmsService.cancelMOForwardResponse> cancelMOForwardAsync(string arg0, string arg1) {
            CRM.App.SendSmsService.cancelMOForwardRequest inValue = new CRM.App.SendSmsService.cancelMOForwardRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((CRM.App.SendSmsService.SDKClient)(this)).cancelMOForwardAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRM.App.SendSmsService.chargeUpResponse CRM.App.SendSmsService.SDKClient.chargeUp(CRM.App.SendSmsService.chargeUpRequest request) {
            return base.Channel.chargeUp(request);
        }
        
        public int chargeUp(string arg0, string arg1, string arg2, string arg3) {
            CRM.App.SendSmsService.chargeUpRequest inValue = new CRM.App.SendSmsService.chargeUpRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            CRM.App.SendSmsService.chargeUpResponse retVal = ((CRM.App.SendSmsService.SDKClient)(this)).chargeUp(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CRM.App.SendSmsService.chargeUpResponse> CRM.App.SendSmsService.SDKClient.chargeUpAsync(CRM.App.SendSmsService.chargeUpRequest request) {
            return base.Channel.chargeUpAsync(request);
        }
        
        public System.Threading.Tasks.Task<CRM.App.SendSmsService.chargeUpResponse> chargeUpAsync(string arg0, string arg1, string arg2, string arg3) {
            CRM.App.SendSmsService.chargeUpRequest inValue = new CRM.App.SendSmsService.chargeUpRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            return ((CRM.App.SendSmsService.SDKClient)(this)).chargeUpAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRM.App.SendSmsService.getBalanceResponse CRM.App.SendSmsService.SDKClient.getBalance(CRM.App.SendSmsService.getBalanceRequest request) {
            return base.Channel.getBalance(request);
        }
        
        public double getBalance(string arg0, string arg1) {
            CRM.App.SendSmsService.getBalanceRequest inValue = new CRM.App.SendSmsService.getBalanceRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            CRM.App.SendSmsService.getBalanceResponse retVal = ((CRM.App.SendSmsService.SDKClient)(this)).getBalance(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CRM.App.SendSmsService.getBalanceResponse> CRM.App.SendSmsService.SDKClient.getBalanceAsync(CRM.App.SendSmsService.getBalanceRequest request) {
            return base.Channel.getBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<CRM.App.SendSmsService.getBalanceResponse> getBalanceAsync(string arg0, string arg1) {
            CRM.App.SendSmsService.getBalanceRequest inValue = new CRM.App.SendSmsService.getBalanceRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((CRM.App.SendSmsService.SDKClient)(this)).getBalanceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRM.App.SendSmsService.getEachFeeResponse CRM.App.SendSmsService.SDKClient.getEachFee(CRM.App.SendSmsService.getEachFeeRequest request) {
            return base.Channel.getEachFee(request);
        }
        
        public double getEachFee(string arg0, string arg1) {
            CRM.App.SendSmsService.getEachFeeRequest inValue = new CRM.App.SendSmsService.getEachFeeRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            CRM.App.SendSmsService.getEachFeeResponse retVal = ((CRM.App.SendSmsService.SDKClient)(this)).getEachFee(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CRM.App.SendSmsService.getEachFeeResponse> CRM.App.SendSmsService.SDKClient.getEachFeeAsync(CRM.App.SendSmsService.getEachFeeRequest request) {
            return base.Channel.getEachFeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<CRM.App.SendSmsService.getEachFeeResponse> getEachFeeAsync(string arg0, string arg1) {
            CRM.App.SendSmsService.getEachFeeRequest inValue = new CRM.App.SendSmsService.getEachFeeRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((CRM.App.SendSmsService.SDKClient)(this)).getEachFeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRM.App.SendSmsService.getMOResponse CRM.App.SendSmsService.SDKClient.getMO(CRM.App.SendSmsService.getMORequest request) {
            return base.Channel.getMO(request);
        }
        
        public CRM.App.SendSmsService.mo[] getMO(string arg0, string arg1) {
            CRM.App.SendSmsService.getMORequest inValue = new CRM.App.SendSmsService.getMORequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            CRM.App.SendSmsService.getMOResponse retVal = ((CRM.App.SendSmsService.SDKClient)(this)).getMO(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CRM.App.SendSmsService.getMOResponse> CRM.App.SendSmsService.SDKClient.getMOAsync(CRM.App.SendSmsService.getMORequest request) {
            return base.Channel.getMOAsync(request);
        }
        
        public System.Threading.Tasks.Task<CRM.App.SendSmsService.getMOResponse> getMOAsync(string arg0, string arg1) {
            CRM.App.SendSmsService.getMORequest inValue = new CRM.App.SendSmsService.getMORequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((CRM.App.SendSmsService.SDKClient)(this)).getMOAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRM.App.SendSmsService.logoutResponse CRM.App.SendSmsService.SDKClient.logout(CRM.App.SendSmsService.logoutRequest request) {
            return base.Channel.logout(request);
        }
        
        public int logout(string arg0, string arg1) {
            CRM.App.SendSmsService.logoutRequest inValue = new CRM.App.SendSmsService.logoutRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            CRM.App.SendSmsService.logoutResponse retVal = ((CRM.App.SendSmsService.SDKClient)(this)).logout(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CRM.App.SendSmsService.logoutResponse> CRM.App.SendSmsService.SDKClient.logoutAsync(CRM.App.SendSmsService.logoutRequest request) {
            return base.Channel.logoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<CRM.App.SendSmsService.logoutResponse> logoutAsync(string arg0, string arg1) {
            CRM.App.SendSmsService.logoutRequest inValue = new CRM.App.SendSmsService.logoutRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((CRM.App.SendSmsService.SDKClient)(this)).logoutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRM.App.SendSmsService.registDetailInfoResponse CRM.App.SendSmsService.SDKClient.registDetailInfo(CRM.App.SendSmsService.registDetailInfoRequest request) {
            return base.Channel.registDetailInfo(request);
        }
        
        public int registDetailInfo(string arg0, string arg1, string arg2, string arg3, string arg4, string arg5, string arg6, string arg7, string arg8, string arg9) {
            CRM.App.SendSmsService.registDetailInfoRequest inValue = new CRM.App.SendSmsService.registDetailInfoRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            inValue.arg5 = arg5;
            inValue.arg6 = arg6;
            inValue.arg7 = arg7;
            inValue.arg8 = arg8;
            inValue.arg9 = arg9;
            CRM.App.SendSmsService.registDetailInfoResponse retVal = ((CRM.App.SendSmsService.SDKClient)(this)).registDetailInfo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CRM.App.SendSmsService.registDetailInfoResponse> CRM.App.SendSmsService.SDKClient.registDetailInfoAsync(CRM.App.SendSmsService.registDetailInfoRequest request) {
            return base.Channel.registDetailInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CRM.App.SendSmsService.registDetailInfoResponse> registDetailInfoAsync(string arg0, string arg1, string arg2, string arg3, string arg4, string arg5, string arg6, string arg7, string arg8, string arg9) {
            CRM.App.SendSmsService.registDetailInfoRequest inValue = new CRM.App.SendSmsService.registDetailInfoRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            inValue.arg5 = arg5;
            inValue.arg6 = arg6;
            inValue.arg7 = arg7;
            inValue.arg8 = arg8;
            inValue.arg9 = arg9;
            return ((CRM.App.SendSmsService.SDKClient)(this)).registDetailInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRM.App.SendSmsService.registExResponse CRM.App.SendSmsService.SDKClient.registEx(CRM.App.SendSmsService.registExRequest request) {
            return base.Channel.registEx(request);
        }
        
        public int registEx(string arg0, string arg1, string arg2) {
            CRM.App.SendSmsService.registExRequest inValue = new CRM.App.SendSmsService.registExRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            CRM.App.SendSmsService.registExResponse retVal = ((CRM.App.SendSmsService.SDKClient)(this)).registEx(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CRM.App.SendSmsService.registExResponse> CRM.App.SendSmsService.SDKClient.registExAsync(CRM.App.SendSmsService.registExRequest request) {
            return base.Channel.registExAsync(request);
        }
        
        public System.Threading.Tasks.Task<CRM.App.SendSmsService.registExResponse> registExAsync(string arg0, string arg1, string arg2) {
            CRM.App.SendSmsService.registExRequest inValue = new CRM.App.SendSmsService.registExRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            return ((CRM.App.SendSmsService.SDKClient)(this)).registExAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRM.App.SendSmsService.sendSMSResponse CRM.App.SendSmsService.SDKClient.sendSMS(CRM.App.SendSmsService.sendSMSRequest request) {
            return base.Channel.sendSMS(request);
        }
        
        public int sendSMS(string arg0, string arg1, string arg2, string[] arg3, string arg4, string arg5, string arg6, int arg7, long arg8) {
            CRM.App.SendSmsService.sendSMSRequest inValue = new CRM.App.SendSmsService.sendSMSRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            inValue.arg5 = arg5;
            inValue.arg6 = arg6;
            inValue.arg7 = arg7;
            inValue.arg8 = arg8;
            CRM.App.SendSmsService.sendSMSResponse retVal = ((CRM.App.SendSmsService.SDKClient)(this)).sendSMS(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CRM.App.SendSmsService.sendSMSResponse> CRM.App.SendSmsService.SDKClient.sendSMSAsync(CRM.App.SendSmsService.sendSMSRequest request) {
            return base.Channel.sendSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<CRM.App.SendSmsService.sendSMSResponse> sendSMSAsync(string arg0, string arg1, string arg2, string[] arg3, string arg4, string arg5, string arg6, int arg7, long arg8) {
            CRM.App.SendSmsService.sendSMSRequest inValue = new CRM.App.SendSmsService.sendSMSRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            inValue.arg5 = arg5;
            inValue.arg6 = arg6;
            inValue.arg7 = arg7;
            inValue.arg8 = arg8;
            return ((CRM.App.SendSmsService.SDKClient)(this)).sendSMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRM.App.SendSmsService.sendVoiceResponse CRM.App.SendSmsService.SDKClient.sendVoice(CRM.App.SendSmsService.sendVoiceRequest request) {
            return base.Channel.sendVoice(request);
        }
        
        public string sendVoice(string arg0, string arg1, string arg2, string[] arg3, string arg4, string arg5, string arg6, int arg7, long arg8) {
            CRM.App.SendSmsService.sendVoiceRequest inValue = new CRM.App.SendSmsService.sendVoiceRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            inValue.arg5 = arg5;
            inValue.arg6 = arg6;
            inValue.arg7 = arg7;
            inValue.arg8 = arg8;
            CRM.App.SendSmsService.sendVoiceResponse retVal = ((CRM.App.SendSmsService.SDKClient)(this)).sendVoice(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CRM.App.SendSmsService.sendVoiceResponse> CRM.App.SendSmsService.SDKClient.sendVoiceAsync(CRM.App.SendSmsService.sendVoiceRequest request) {
            return base.Channel.sendVoiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<CRM.App.SendSmsService.sendVoiceResponse> sendVoiceAsync(string arg0, string arg1, string arg2, string[] arg3, string arg4, string arg5, string arg6, int arg7, long arg8) {
            CRM.App.SendSmsService.sendVoiceRequest inValue = new CRM.App.SendSmsService.sendVoiceRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            inValue.arg5 = arg5;
            inValue.arg6 = arg6;
            inValue.arg7 = arg7;
            inValue.arg8 = arg8;
            return ((CRM.App.SendSmsService.SDKClient)(this)).sendVoiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRM.App.SendSmsService.serialPwdUpdResponse CRM.App.SendSmsService.SDKClient.serialPwdUpd(CRM.App.SendSmsService.serialPwdUpdRequest request) {
            return base.Channel.serialPwdUpd(request);
        }
        
        public int serialPwdUpd(string arg0, string arg1, string arg2, string arg3) {
            CRM.App.SendSmsService.serialPwdUpdRequest inValue = new CRM.App.SendSmsService.serialPwdUpdRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            CRM.App.SendSmsService.serialPwdUpdResponse retVal = ((CRM.App.SendSmsService.SDKClient)(this)).serialPwdUpd(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CRM.App.SendSmsService.serialPwdUpdResponse> CRM.App.SendSmsService.SDKClient.serialPwdUpdAsync(CRM.App.SendSmsService.serialPwdUpdRequest request) {
            return base.Channel.serialPwdUpdAsync(request);
        }
        
        public System.Threading.Tasks.Task<CRM.App.SendSmsService.serialPwdUpdResponse> serialPwdUpdAsync(string arg0, string arg1, string arg2, string arg3) {
            CRM.App.SendSmsService.serialPwdUpdRequest inValue = new CRM.App.SendSmsService.serialPwdUpdRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            return ((CRM.App.SendSmsService.SDKClient)(this)).serialPwdUpdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRM.App.SendSmsService.setMOForwardResponse CRM.App.SendSmsService.SDKClient.setMOForward(CRM.App.SendSmsService.setMOForwardRequest request) {
            return base.Channel.setMOForward(request);
        }
        
        public int setMOForward(string arg0, string arg1, string arg2) {
            CRM.App.SendSmsService.setMOForwardRequest inValue = new CRM.App.SendSmsService.setMOForwardRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            CRM.App.SendSmsService.setMOForwardResponse retVal = ((CRM.App.SendSmsService.SDKClient)(this)).setMOForward(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CRM.App.SendSmsService.setMOForwardResponse> CRM.App.SendSmsService.SDKClient.setMOForwardAsync(CRM.App.SendSmsService.setMOForwardRequest request) {
            return base.Channel.setMOForwardAsync(request);
        }
        
        public System.Threading.Tasks.Task<CRM.App.SendSmsService.setMOForwardResponse> setMOForwardAsync(string arg0, string arg1, string arg2) {
            CRM.App.SendSmsService.setMOForwardRequest inValue = new CRM.App.SendSmsService.setMOForwardRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            return ((CRM.App.SendSmsService.SDKClient)(this)).setMOForwardAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRM.App.SendSmsService.setMOForwardExResponse CRM.App.SendSmsService.SDKClient.setMOForwardEx(CRM.App.SendSmsService.setMOForwardExRequest request) {
            return base.Channel.setMOForwardEx(request);
        }
        
        public int setMOForwardEx(string arg0, string arg1, string[] arg2) {
            CRM.App.SendSmsService.setMOForwardExRequest inValue = new CRM.App.SendSmsService.setMOForwardExRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            CRM.App.SendSmsService.setMOForwardExResponse retVal = ((CRM.App.SendSmsService.SDKClient)(this)).setMOForwardEx(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CRM.App.SendSmsService.setMOForwardExResponse> CRM.App.SendSmsService.SDKClient.setMOForwardExAsync(CRM.App.SendSmsService.setMOForwardExRequest request) {
            return base.Channel.setMOForwardExAsync(request);
        }
        
        public System.Threading.Tasks.Task<CRM.App.SendSmsService.setMOForwardExResponse> setMOForwardExAsync(string arg0, string arg1, string[] arg2) {
            CRM.App.SendSmsService.setMOForwardExRequest inValue = new CRM.App.SendSmsService.setMOForwardExRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            return ((CRM.App.SendSmsService.SDKClient)(this)).setMOForwardExAsync(inValue);
        }
    }
}
