//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_CRMEntities : DbContext
    {
        public DB_CRMEntities()
            : base("name=DB_CRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FileUploader> FileUploader { get; set; }
        public virtual DbSet<SysAnnouncement> SysAnnouncement { get; set; }
        public virtual DbSet<SysCodeTable> SysCodeTable { get; set; }
        public virtual DbSet<SysColumnFilter> SysColumnFilter { get; set; }
        public virtual DbSet<SysDepartment> SysDepartment { get; set; }
        public virtual DbSet<SysDocument> SysDocument { get; set; }
        public virtual DbSet<SysDocumentTalk> SysDocumentTalk { get; set; }
        public virtual DbSet<SysEmail> SysEmail { get; set; }
        public virtual DbSet<SysEmailTemp> SysEmailTemp { get; set; }
        public virtual DbSet<SysException> SysException { get; set; }
        public virtual DbSet<SysField> SysField { get; set; }
        public virtual DbSet<SysLog> SysLog { get; set; }
        public virtual DbSet<SysMenu> SysMenu { get; set; }
        public virtual DbSet<SysMenuSysRoleSysOperation> SysMenuSysRoleSysOperation { get; set; }
        public virtual DbSet<SysMessage> SysMessage { get; set; }
        public virtual DbSet<SysMessageTemp> SysMessageTemp { get; set; }
        public virtual DbSet<SysNotice> SysNotice { get; set; }
        public virtual DbSet<SysOperation> SysOperation { get; set; }
        public virtual DbSet<SysPerson> SysPerson { get; set; }
        public virtual DbSet<SysRole> SysRole { get; set; }
        public virtual DbSet<TB_Address> TB_Address { get; set; }
        public virtual DbSet<TB_Billing> TB_Billing { get; set; }
        public virtual DbSet<TB_BillingDetails> TB_BillingDetails { get; set; }
        public virtual DbSet<TB_CallLog> TB_CallLog { get; set; }
        public virtual DbSet<TB_Company> TB_Company { get; set; }
        public virtual DbSet<TB_CompanyInterviewJob> TB_CompanyInterviewJob { get; set; }
        public virtual DbSet<TB_Contract> TB_Contract { get; set; }
        public virtual DbSet<TB_ContractSolution> TB_ContractSolution { get; set; }
        public virtual DbSet<TB_Customer> TB_Customer { get; set; }
        public virtual DbSet<TB_CustomerAttributionChange> TB_CustomerAttributionChange { get; set; }
        public virtual DbSet<TB_CustomerContact> TB_CustomerContact { get; set; }
        public virtual DbSet<TB_CustomerFollow> TB_CustomerFollow { get; set; }
        public virtual DbSet<TB_CustomerFollowSolution> TB_CustomerFollowSolution { get; set; }
        public virtual DbSet<TB_CustomerProject> TB_CustomerProject { get; set; }
        public virtual DbSet<TB_CustomerProjectEvalDetails> TB_CustomerProjectEvalDetails { get; set; }
        public virtual DbSet<TB_CustomerRating> TB_CustomerRating { get; set; }
        public virtual DbSet<TB_CustomerService> TB_CustomerService { get; set; }
        public virtual DbSet<TB_CustomerShare> TB_CustomerShare { get; set; }
        public virtual DbSet<TB_CustomerShareLog> TB_CustomerShareLog { get; set; }
        public virtual DbSet<TB_CustomerVerification> TB_CustomerVerification { get; set; }
        public virtual DbSet<TB_ImportResume> TB_ImportResume { get; set; }
        public virtual DbSet<TB_JobhunterResumeInterview> TB_JobhunterResumeInterview { get; set; }
        public virtual DbSet<TB_RecommendSolution> TB_RecommendSolution { get; set; }
        public virtual DbSet<TB_RPOPerformance> TB_RPOPerformance { get; set; }
        public virtual DbSet<TB_SalesPerformance> TB_SalesPerformance { get; set; }
        public virtual DbSet<TP_Employees> TP_Employees { get; set; }
        public virtual DbSet<TP_HousingFund> TP_HousingFund { get; set; }
        public virtual DbSet<TP_SalaryDetails> TP_SalaryDetails { get; set; }
        public virtual DbSet<TP_SalaryItem> TP_SalaryItem { get; set; }
        public virtual DbSet<TP_SalarySubjectSysPerson> TP_SalarySubjectSysPerson { get; set; }
        public virtual DbSet<TP_SocialInsur> TP_SocialInsur { get; set; }
        public virtual DbSet<TP_SubjectsAuthority> TP_SubjectsAuthority { get; set; }
        public virtual DbSet<TB_SoundComment> TB_SoundComment { get; set; }
    }
}
