//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysDepartment
    {
        public SysDepartment()
        {
    	
    			//------------------------------------------------------------------------------
                // <auto-generated>
                //     此代码已从模板生成。  create by chand 2016-04-13
                //
                //     手动更改此文件可能导致应用程序出现意外的行为。
                //     如果重新生成代码，将覆盖对此文件的手动更改。
                // </auto-generated>
                //------------------------------------------------------------------------------
    			this.Id = String.Empty;
    				this.Name = String.Empty;
    				this.ParentId = String.Empty;
    				this.PositionLevel = String.Empty;
    				this.Address = String.Empty;
    				this.Sort =0;
    				this.Remark = String.Empty;
    				this.CreateTime = DateTime.Now;
    				this.CreatePerson = String.Empty;
    				this.UpdateTime = DateTime.Now;
    				this.UpdatePerson = String.Empty;
    		
    
            this.SysDepartment1 = new HashSet<SysDepartment>();
            this.SysPerson = new HashSet<SysPerson>();
            this.SysDocument = new HashSet<SysDocument>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string ParentId { get; set; }
        public string PositionLevel { get; set; }
        public string Address { get; set; }
        public Nullable<int> Sort { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreatePerson { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdatePerson { get; set; }
    
        public virtual ICollection<SysDepartment> SysDepartment1 { get; set; }
        public virtual SysDepartment SysDepartment2 { get; set; }
        public virtual ICollection<SysPerson> SysPerson { get; set; }
        public virtual ICollection<SysDocument> SysDocument { get; set; }
    }
}
