//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysEmail
    {
    	
    	  public SysEmail()
        {
    
    			//------------------------------------------------------------------------------
                // <auto-generated>
                //     此代码已从模板生成。  create by chand 2016-04-13
                //
                //     手动更改此文件可能导致应用程序出现意外的行为。
                //     如果重新生成代码，将覆盖对此文件的手动更改。
                // </auto-generated>
                //------------------------------------------------------------------------------
    			this.Id = String.Empty;
    				this.SysMailId = String.Empty;
    				this.Subject = String.Empty;
    				this.Content = String.Empty;
    				this.Reply_email = String.Empty;
    				this.Mail_type = String.Empty;
    				this.Remark = String.Empty;
    				this.State = String.Empty;
    				this.ReadTime = DateTime.Now;
    				this.CreateTime = DateTime.Now;
    				this.CreatePerson = String.Empty;
    		
    
    
    	}
    	    public string Id { get; set; }
        public string SysMailId { get; set; }
        public string Subject { get; set; }
        public string Content { get; set; }
        public string Reply_email { get; set; }
        public string Mail_type { get; set; }
        public string Remark { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> ReadTime { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreatePerson { get; set; }
    
        public virtual SysEmailTemp SysEmailTemp { get; set; }
    }
}
