//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysField
    {
        public SysField()
        {
    	
    			//------------------------------------------------------------------------------
                // <auto-generated>
                //     此代码已从模板生成。  create by chand 2016-04-13
                //
                //     手动更改此文件可能导致应用程序出现意外的行为。
                //     如果重新生成代码，将覆盖对此文件的手动更改。
                // </auto-generated>
                //------------------------------------------------------------------------------
    			this.Id = String.Empty;
    				this.MyTexts = String.Empty;
    				this.DataValue = String.Empty;
    				this.ParentId = String.Empty;
    				this.MyTables = String.Empty;
    				this.MyColums = String.Empty;
    				this.Sort =0;
    				this.Remark = String.Empty;
    				this.CreateTime = DateTime.Now;
    				this.CreatePerson = String.Empty;
    				this.UpdateTime = DateTime.Now;
    				this.UpdatePerson = String.Empty;
    		
    
            this.SysField1 = new HashSet<SysField>();
        }
    
        public string Id { get; set; }
        public string MyTexts { get; set; }
        public string DataValue { get; set; }
        public string ParentId { get; set; }
        public string MyTables { get; set; }
        public string MyColums { get; set; }
        public Nullable<int> Sort { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreatePerson { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdatePerson { get; set; }
    
        public virtual ICollection<SysField> SysField1 { get; set; }
        public virtual SysField SysField2 { get; set; }
    }
}
