//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysMenuSysRoleSysOperation
    {
    	
    	  public SysMenuSysRoleSysOperation()
        {
    
    			//------------------------------------------------------------------------------
                // <auto-generated>
                //     此代码已从模板生成。  create by chand 2016-04-13
                //
                //     手动更改此文件可能导致应用程序出现意外的行为。
                //     如果重新生成代码，将覆盖对此文件的手动更改。
                // </auto-generated>
                //------------------------------------------------------------------------------
    			this.Id = String.Empty;
    				this.SysMenuId = String.Empty;
    				this.SysOperationId = String.Empty;
    				this.SysRoleId = String.Empty;
    		
    
    
    	}
    	    public string Id { get; set; }
        public string SysMenuId { get; set; }
        public string SysOperationId { get; set; }
        public string SysRoleId { get; set; }
    
        public virtual SysMenu SysMenu { get; set; }
        public virtual SysOperation SysOperation { get; set; }
        public virtual SysRole SysRole { get; set; }
    }
}
