//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysOperation
    {
        public SysOperation()
        {
    	
    			//------------------------------------------------------------------------------
                // <auto-generated>
                //     此代码已从模板生成。  create by chand 2016-04-13
                //
                //     手动更改此文件可能导致应用程序出现意外的行为。
                //     如果重新生成代码，将覆盖对此文件的手动更改。
                // </auto-generated>
                //------------------------------------------------------------------------------
    			this.Id = String.Empty;
    				this.Name = String.Empty;
    				this.Function = String.Empty;
    				this.Iconic = String.Empty;
    				this.Sort =0;
    				this.Remark = String.Empty;
    				this.State = String.Empty;
    				this.CreateTime = DateTime.Now;
    				this.CreatePerson = String.Empty;
    		
    
            this.SysMenuSysRoleSysOperation = new HashSet<SysMenuSysRoleSysOperation>();
            this.SysMenu = new HashSet<SysMenu>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string Function { get; set; }
        public string Iconic { get; set; }
        public Nullable<int> Sort { get; set; }
        public string Remark { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreatePerson { get; set; }
    
        public virtual ICollection<SysMenuSysRoleSysOperation> SysMenuSysRoleSysOperation { get; set; }
        public virtual SysOperation SysOperation1 { get; set; }
        public virtual SysOperation SysOperation2 { get; set; }
        public virtual ICollection<SysMenu> SysMenu { get; set; }
    }
}
