//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Customer
    {
        public TB_Customer()
        {
    	
    			//------------------------------------------------------------------------------
                // <auto-generated>
                //     此代码已从模板生成。  create by chand 2016-04-13
                //
                //     手动更改此文件可能导致应用程序出现意外的行为。
                //     如果重新生成代码，将覆盖对此文件的手动更改。
                // </auto-generated>
                //------------------------------------------------------------------------------
    			this.CustomerID = String.Empty;
    				this.CustomerName = String.Empty;
    				this.CompanyNatureCode = String.Empty;
    				this.EstablishDate = DateTime.Now;
    				this.VocationCode = String.Empty;
    				this.VocationName = String.Empty;
    				this.ProvinceCode = String.Empty;
    				this.ProvinceName = String.Empty;
    				this.CityCode = String.Empty;
    				this.CityName = String.Empty;
    				this.DistrictCode = String.Empty;
    				this.DistrictName = String.Empty;
    				this.AddressDetails = String.Empty;
    				this.CustomerLevel = String.Empty;
    				this.CustomerFunnel = String.Empty;
    				this.FollowUpDate = DateTime.Now;
    				this.ContactPerson = String.Empty;
    				this.ContactPhone = String.Empty;
    				this.ContactTel = String.Empty;
    				this.EmailAddress = String.Empty;
    				this.PositionLink = String.Empty;
    				this.IsRegister =false;
    				this.IsCertification =false;
    				this.ReleaseState = String.Empty;
    				this.HomePage = String.Empty;
    				this.Comments = String.Empty;
    				this.CompanyStatusCode = String.Empty;
    				this.CompanyPreview = String.Empty;
    				this.CompanyCertification = String.Empty;
    				this.Opportunities = String.Empty;
    				this.FollowBack = String.Empty;
    				this.SocialRecruitingQty =0;
    				this.SchoolRecruitingQty =0;
    				this.Package = String.Empty;
    				this.SysPersonID = String.Empty;
    				this.BelongingDate = DateTime.Now;
    				this.RelieveDate = DateTime.Now;
    				this.CompanyID =0;
    				this.CompanyName = String.Empty;
    				this.IsFrozen =false;
    				this.IsDelete =false;
    				this.VersionNo =0;
    				this.CreatedBy = String.Empty;
    				this.CreatedTime = DateTime.Now;
    				this.LastUpdatedBy = String.Empty;
    				this.LastUpdatedTime = DateTime.Now;
    				this.AuditStatus =0;
    				this.AuditPerson = String.Empty;
    				this.AuditTime = DateTime.Now;
    				this.Reason = String.Empty;
    				this.CustomerFunnel2 = String.Empty;
    				this.FollowUpDate2 = DateTime.Now;
    				this.Opportunities2 = String.Empty;
    				this.FollowBack2 = String.Empty;
    				this.FollowUpMode = String.Empty;
    				this.FollowUpMode2 = String.Empty;
    				this.IsSalary =false;
    				this.CompanySize = String.Empty;
    				this.RegisterCapital = String.Empty;
    				this.SalesRevenue = String.Empty;
    				this.RatingScore = String.Empty;
    				this.CustomerSource = String.Empty;
    				this.WeekOfYear =0;
    		
    
            this.TB_CallLog = new HashSet<TB_CallLog>();
            this.TB_CustomerAttributionChange = new HashSet<TB_CustomerAttributionChange>();
            this.TB_CustomerContact = new HashSet<TB_CustomerContact>();
            this.TB_CustomerShare = new HashSet<TB_CustomerShare>();
        }
    
        public string CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string CompanyNatureCode { get; set; }
        public Nullable<System.DateTime> EstablishDate { get; set; }
        public string VocationCode { get; set; }
        public string VocationName { get; set; }
        public string ProvinceCode { get; set; }
        public string ProvinceName { get; set; }
        public string CityCode { get; set; }
        public string CityName { get; set; }
        public string DistrictCode { get; set; }
        public string DistrictName { get; set; }
        public string AddressDetails { get; set; }
        public string CustomerLevel { get; set; }
        public string CustomerFunnel { get; set; }
        public Nullable<System.DateTime> FollowUpDate { get; set; }
        public string ContactPerson { get; set; }
        public string ContactPhone { get; set; }
        public string ContactTel { get; set; }
        public string EmailAddress { get; set; }
        public string PositionLink { get; set; }
        public Nullable<bool> IsRegister { get; set; }
        public Nullable<bool> IsCertification { get; set; }
        public string ReleaseState { get; set; }
        public string HomePage { get; set; }
        public string Comments { get; set; }
        public string CompanyStatusCode { get; set; }
        public string CompanyPreview { get; set; }
        public string CompanyCertification { get; set; }
        public string Opportunities { get; set; }
        public string FollowBack { get; set; }
        public Nullable<int> SocialRecruitingQty { get; set; }
        public Nullable<int> SchoolRecruitingQty { get; set; }
        public string Package { get; set; }
        public string SysPersonID { get; set; }
        public Nullable<System.DateTime> BelongingDate { get; set; }
        public Nullable<System.DateTime> RelieveDate { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string CompanyName { get; set; }
        public bool IsFrozen { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> VersionNo { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
        public Nullable<int> AuditStatus { get; set; }
        public string AuditPerson { get; set; }
        public Nullable<System.DateTime> AuditTime { get; set; }
        public string Reason { get; set; }
        public string CustomerFunnel2 { get; set; }
        public Nullable<System.DateTime> FollowUpDate2 { get; set; }
        public string Opportunities2 { get; set; }
        public string FollowBack2 { get; set; }
        public string FollowUpMode { get; set; }
        public string FollowUpMode2 { get; set; }
        public Nullable<bool> IsSalary { get; set; }
        public Nullable<short> Source { get; set; }
        public string CompanySize { get; set; }
        public string RegisterCapital { get; set; }
        public string SalesRevenue { get; set; }
        public string RatingScore { get; set; }
        public string CustomerSource { get; set; }
        public Nullable<int> WeekOfYear { get; set; }
    
        public virtual ICollection<TB_CallLog> TB_CallLog { get; set; }
        public virtual ICollection<TB_CustomerAttributionChange> TB_CustomerAttributionChange { get; set; }
        public virtual ICollection<TB_CustomerContact> TB_CustomerContact { get; set; }
        public virtual ICollection<TB_CustomerShare> TB_CustomerShare { get; set; }
    }
}
