//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CustomerShareLog
    {
    	
    	  public TB_CustomerShareLog()
        {
    
    			//------------------------------------------------------------------------------
                // <auto-generated>
                //     此代码已从模板生成。  create by chand 2016-04-13
                //
                //     手动更改此文件可能导致应用程序出现意外的行为。
                //     如果重新生成代码，将覆盖对此文件的手动更改。
                // </auto-generated>
                //------------------------------------------------------------------------------
    			this.CustomerShareLogID =0;
    				this.CustomerID = String.Empty;
    				this.SysPersonIDFrom = String.Empty;
    				this.SysPersonIDTo = String.Empty;
    				this.ShareRemark = String.Empty;
    				this.IsDelete =false;
    				this.VersionNo =0;
    				this.CreatedTime = DateTime.Now;
    				this.CreatedBy = String.Empty;
    				this.LastUpdatedTime = DateTime.Now;
    				this.LastUpdatedBy = String.Empty;
    		
    
    
    	}
    	    public long CustomerShareLogID { get; set; }
        public string CustomerID { get; set; }
        public string SysPersonIDFrom { get; set; }
        public string SysPersonIDTo { get; set; }
        public string ShareRemark { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> VersionNo { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
        public string LastUpdatedBy { get; set; }
    }
}
