//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Company
    {
    	
    	  public TB_Company()
        {
    
    			//------------------------------------------------------------------------------
                // <auto-generated>
                //     此代码已从模板生成。  create by chand 2016-04-13
                //
                //     手动更改此文件可能导致应用程序出现意外的行为。
                //     如果重新生成代码，将覆盖对此文件的手动更改。
                // </auto-generated>
                //------------------------------------------------------------------------------
    			this.CompanyID =0;
    				this.CompanyName = String.Empty;
    				this.CompanyNatureCode = String.Empty;
    				this.VocationCode = String.Empty;
    				this.SubVocationCode = String.Empty;
    				this.FoundAccountCode = String.Empty;
    				this.CompanyScaleCode = String.Empty;
    				this.HomePage = String.Empty;
    				this.OtherLink = String.Empty;
    				this.AddressID =0;
    				this.Comments = String.Empty;
    				this.CompanyStatusCode = String.Empty;
    				this.HRUserInformationID =0;
    				this.CompanyPreview = String.Empty;
    				this.CompanyCertification = String.Empty;
    				this.CompanyCertificationTypeCode = String.Empty;
    				this.VersionNo =0;
    				this.TransactionID = String.Empty;
    				this.CreatedBy = String.Empty;
    				this.LastUpdatedBy = String.Empty;
    				this.RunCompanyName = String.Empty;
    				this.TravelRoute = String.Empty;
    				this.CompanyPreview2 = String.Empty;
    				this.Other1UserInformationID =0;
    				this.Other2UserInformationID =0;
    				this.CheckedBy = String.Empty;
    				this.CheckedTime = DateTime.Now;
    				this.CompanyOrganizationCodeCertification = String.Empty;
    				this.CheckNoPassReason = String.Empty;
    				this.IsMember =false;
    				this.IsIndexPartner =false;
    				this.CompanyRemark = String.Empty;
    				this.PublicCompanyStatus = String.Empty;
    				this.CompanyEnglishName = String.Empty;
    				this.CompanyVideo = String.Empty;
    				this.CompanySlogan = String.Empty;
    				this.IsDeleted =false;
    		
    
    
    	}
    	    public int CompanyID { get; set; }
        public string CompanyName { get; set; }
        public string CompanyNatureCode { get; set; }
        public System.DateTime EstablishDateCode { get; set; }
        public string VocationCode { get; set; }
        public string SubVocationCode { get; set; }
        public string FoundAccountCode { get; set; }
        public string CompanyScaleCode { get; set; }
        public string HomePage { get; set; }
        public string OtherLink { get; set; }
        public int AddressID { get; set; }
        public string Comments { get; set; }
        public string CompanyStatusCode { get; set; }
        public Nullable<int> HRUserInformationID { get; set; }
        public string CompanyPreview { get; set; }
        public string CompanyCertification { get; set; }
        public string CompanyCertificationTypeCode { get; set; }
        public int VersionNo { get; set; }
        public string TransactionID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string LastUpdatedBy { get; set; }
        public System.DateTime LastUpdatedTime { get; set; }
        public string RunCompanyName { get; set; }
        public string TravelRoute { get; set; }
        public string CompanyPreview2 { get; set; }
        public Nullable<int> Other1UserInformationID { get; set; }
        public Nullable<int> Other2UserInformationID { get; set; }
        public string CheckedBy { get; set; }
        public Nullable<System.DateTime> CheckedTime { get; set; }
        public string CompanyOrganizationCodeCertification { get; set; }
        public string CheckNoPassReason { get; set; }
        public Nullable<bool> IsMember { get; set; }
        public Nullable<bool> IsIndexPartner { get; set; }
        public string CompanyRemark { get; set; }
        public string PublicCompanyStatus { get; set; }
        public string CompanyEnglishName { get; set; }
        public string CompanyVideo { get; set; }
        public string CompanySlogan { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
