//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ImportResume
    {
    	
    	  public TB_ImportResume()
        {
    
    			//------------------------------------------------------------------------------
                // <auto-generated>
                //     此代码已从模板生成。  create by chand 2016-04-13
                //
                //     手动更改此文件可能导致应用程序出现意外的行为。
                //     如果重新生成代码，将覆盖对此文件的手动更改。
                // </auto-generated>
                //------------------------------------------------------------------------------
    			this.ImportResumeID = String.Empty;
    				this.SysPersonID = String.Empty;
    				this.OfferUserID = String.Empty;
    				this.ResumeName = String.Empty;
    				this.GenderCode =0;
    				this.BOB = DateTime.Now;
    				this.AddressID = String.Empty;
    				this.PhoneNumber = String.Empty;
    				this.EmailAddress = String.Empty;
    				this.QQID = String.Empty;
    				this.EducationCode = String.Empty;
    				this.JobSalaryCode = String.Empty;
    				this.JobStatusCode = String.Empty;
    				this.SpecialtyCode = String.Empty;
    				this.Graduated = String.Empty;
    				this.PoliticalCode = String.Empty;
    				this.CredentialsCode = String.Empty;
    				this.MarrigeCode = String.Empty;
    				this.WorkYearCode = String.Empty;
    				this.ResumeSource =0;
    				this.ResumeContent = String.Empty;
    				this.CVLevel =0;
    				this.CallCount =0;
    				this.IsDel =false;
    				this.CreatedTime = DateTime.Now;
    				this.CreatedBy = String.Empty;
    				this.LastUpdatedTime = DateTime.Now;
    				this.LastUpdatedBy = String.Empty;
    		
    
    
    	}
    	    public string ImportResumeID { get; set; }
        public string SysPersonID { get; set; }
        public string OfferUserID { get; set; }
        public string ResumeName { get; set; }
        public Nullable<int> GenderCode { get; set; }
        public Nullable<System.DateTime> BOB { get; set; }
        public string AddressID { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailAddress { get; set; }
        public string QQID { get; set; }
        public string EducationCode { get; set; }
        public string JobSalaryCode { get; set; }
        public string JobStatusCode { get; set; }
        public string SpecialtyCode { get; set; }
        public string Graduated { get; set; }
        public string PoliticalCode { get; set; }
        public string CredentialsCode { get; set; }
        public string MarrigeCode { get; set; }
        public string WorkYearCode { get; set; }
        public Nullable<int> ResumeSource { get; set; }
        public string ResumeContent { get; set; }
        public Nullable<int> CVLevel { get; set; }
        public Nullable<int> CallCount { get; set; }
        public Nullable<bool> IsDel { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
        public string LastUpdatedBy { get; set; }
    }
}
