//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_JobhunterResumeInterview
    {
    	
    	  public TB_JobhunterResumeInterview()
        {
    
    			//------------------------------------------------------------------------------
                // <auto-generated>
                //     此代码已从模板生成。  create by chand 2016-04-13
                //
                //     手动更改此文件可能导致应用程序出现意外的行为。
                //     如果重新生成代码，将覆盖对此文件的手动更改。
                // </auto-generated>
                //------------------------------------------------------------------------------
    			this.JobhunterResumeInterviewID =0;
    				this.CompanyInterviewJobID =0;
    				this.JobhunterResumeID =0;
    				this.Score =0;
    				this.Comments = String.Empty;
    				this.IsReviewed =false;
    				this.VersionNo =0;
    				this.TransactionID = String.Empty;
    				this.CreatedBy = String.Empty;
    				this.LastUpdatedBy = String.Empty;
    				this.ResumeID =0;
    				this.IsDelete =false;
    				this.SendType =0;
    				this.consultantID = String.Empty;
    				this.consultantName = String.Empty;
    				this.IsPending =false;
    		
    
    
    	}
    	    public int JobhunterResumeInterviewID { get; set; }
        public Nullable<int> CompanyInterviewJobID { get; set; }
        public Nullable<int> JobhunterResumeID { get; set; }
        public Nullable<decimal> Score { get; set; }
        public string Comments { get; set; }
        public bool IsReviewed { get; set; }
        public int VersionNo { get; set; }
        public string TransactionID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string LastUpdatedBy { get; set; }
        public System.DateTime LastUpdatedTime { get; set; }
        public Nullable<int> ResumeID { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<int> SendType { get; set; }
        public string consultantID { get; set; }
        public string consultantName { get; set; }
        public Nullable<bool> IsPending { get; set; }
    }
}
