//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TP_Employees
    {
    	
    	  public TP_Employees()
        {
    
    			//------------------------------------------------------------------------------
                // <auto-generated>
                //     此代码已从模板生成。  create by chand 2016-04-13
                //
                //     手动更改此文件可能导致应用程序出现意外的行为。
                //     如果重新生成代码，将覆盖对此文件的手动更改。
                // </auto-generated>
                //------------------------------------------------------------------------------
    			this.EmpID = String.Empty;
    				this.EmpName = String.Empty;
    				this.CustomerID = String.Empty;
    				this.BankType = String.Empty;
    				this.BankCity = String.Empty;
    				this.BankID = String.Empty;
    				this.Birthday = DateTime.Now;
    				this.PhoneNumber = String.Empty;
    				this.EmailAddress = String.Empty;
    				this.Nation = String.Empty;
    				this.IDType = String.Empty;
    				this.IDCard = String.Empty;
    				this.IDCardPic1 = String.Empty;
    				this.IDCardPic2 = String.Empty;
    				this.IDCardPic3 = String.Empty;
    				this.ContractSubject = String.Empty;
    				this.WagesSubject = String.Empty;
    				this.SocialSecuritySubject = String.Empty;
    				this.TaxSubject = String.Empty;
    				this.IsDelete =false;
    				this.VersionNo =0;
    				this.CreatedBy = String.Empty;
    				this.CreatedTime = DateTime.Now;
    				this.LastUpdatedBy = String.Empty;
    				this.LastUpdatedTime = DateTime.Now;
    				this.SocialInsurID = String.Empty;
    				this.HousingFundID = String.Empty;
    		
    
    
    	}
    	    public string EmpID { get; set; }
        public string EmpName { get; set; }
        public string CustomerID { get; set; }
        public Nullable<short> Gender { get; set; }
        public short JobStatus { get; set; }
        public string BankType { get; set; }
        public string BankCity { get; set; }
        public string BankID { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailAddress { get; set; }
        public string Nation { get; set; }
        public string IDType { get; set; }
        public string IDCard { get; set; }
        public string IDCardPic1 { get; set; }
        public string IDCardPic2 { get; set; }
        public string IDCardPic3 { get; set; }
        public string ContractSubject { get; set; }
        public string WagesSubject { get; set; }
        public string SocialSecuritySubject { get; set; }
        public string TaxSubject { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> VersionNo { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
        public string SocialInsurID { get; set; }
        public string HousingFundID { get; set; }
    }
}
