//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TP_HousingFund
    {
    	
    	  public TP_HousingFund()
        {
    
    			//------------------------------------------------------------------------------
                // <auto-generated>
                //     此代码已从模板生成。  create by chand 2016-04-13
                //
                //     手动更改此文件可能导致应用程序出现意外的行为。
                //     如果重新生成代码，将覆盖对此文件的手动更改。
                // </auto-generated>
                //------------------------------------------------------------------------------
    			this.HousingFundID = String.Empty;
    				this.HousingFundName = String.Empty;
    				this.ProvinceCode = String.Empty;
    				this.CityCode = String.Empty;
    				this.DistrictCode = String.Empty;
    				this.DiffBegin =0;
    				this.DiffEnd =0;
    				this.IndiRatio =0;
    				this.CompanyRatio =0;
    				this.IsDelete =false;
    				this.VersionNo =0;
    				this.CreatedBy = String.Empty;
    				this.CreatedTime = DateTime.Now;
    				this.LastUpdatedBy = String.Empty;
    				this.LastUpdatedTime = DateTime.Now;
    		
    
    
    	}
    	    public string HousingFundID { get; set; }
        public string HousingFundName { get; set; }
        public string ProvinceCode { get; set; }
        public string CityCode { get; set; }
        public string DistrictCode { get; set; }
        public Nullable<decimal> DiffBegin { get; set; }
        public Nullable<decimal> DiffEnd { get; set; }
        public Nullable<decimal> IndiRatio { get; set; }
        public Nullable<decimal> CompanyRatio { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> VersionNo { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
