//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TP_SalaryDetails
    {
    	
    	  public TP_SalaryDetails()
        {
    
    			//------------------------------------------------------------------------------
                // <auto-generated>
                //     此代码已从模板生成。  create by chand 2016-04-13
                //
                //     手动更改此文件可能导致应用程序出现意外的行为。
                //     如果重新生成代码，将覆盖对此文件的手动更改。
                // </auto-generated>
                //------------------------------------------------------------------------------
    			this.SalaryDetailsID = String.Empty;
    				this.EmpID = String.Empty;
    				this.SalaryMonth =0;
    				this.CustomerID = String.Empty;
    				this.PayableSalary1 =0;
    				this.IndiPension1 =0;
    				this.IndiMedical1 =0;
    				this.IndiJobSecurity1 =0;
    				this.IndiSSTotal1 =0;
    				this.IndiFund1 =0;
    				this.Tax1 =0;
    				this.AnnualBonus1 =0;
    				this.AnnualBonusTax1 =0;
    				this.RealSalary1 =0;
    				this.CompanyPension1 =0;
    				this.CompanyMedical1 =0;
    				this.CompanyJobSecurity1 =0;
    				this.IndusInsurance1 =0;
    				this.BirthInsurance1 =0;
    				this.CompanySSTotal1 =0;
    				this.Remark1 = String.Empty;
    				this.PayableSalary2 =0;
    				this.TranSubsidies2 =0;
    				this.MealAllowance2 =0;
    				this.TravelAllowance2 =0;
    				this.BackPay2 =0;
    				this.PayableTotal2 =0;
    				this.IndiFund2 =0;
    				this.IndiSSTotal2 =0;
    				this.IndiPension2 =0;
    				this.IndiMedical2 =0;
    				this.IndiJobSecurity2 =0;
    				this.Other2 =0;
    				this.Tax2 =0;
    				this.TaxDeductions2 =0;
    				this.RealSalary2 =0;
    				this.PaymentMode2 = String.Empty;
    				this.Remark2 = String.Empty;
    				this.PayBaseBK3 =0;
    				this.PayBase3 =0;
    				this.CompanyPension3 =0;
    				this.CompanyMedical3 =0;
    				this.CompanyJobSecurity3 =0;
    				this.CompanyInjury3 =0;
    				this.CompanyBirth3 =0;
    				this.CompanySSTotal3 =0;
    				this.CompanyPensionBK3 =0;
    				this.CompanyMedicalBK3 =0;
    				this.CompanyJobSecurityBK3 =0;
    				this.IndusInsuranceBK3 =0;
    				this.BirthInsuranceBK3 =0;
    				this.CompanySSTotalBK3 =0;
    				this.IndiPension3 =0;
    				this.IndiMedical3 =0;
    				this.IndiJobSecurity3 =0;
    				this.IndiSubtotal3 =0;
    				this.IndiPensionBK3 =0;
    				this.IndiMedicalBK3 =0;
    				this.IndiJobSecurityBK3 =0;
    				this.IndiSubtotalBK3 =0;
    				this.Total3 =0;
    				this.SalaryMonthBK3 =0;
    				this.FundAccount3 =0;
    				this.IndiFund3 =0;
    				this.CompanyFund3 =0;
    				this.FundSubtotal3 =0;
    				this.PayAmount3 =0;
    				this.FundAccountBC3 =0;
    				this.IndiFundBC3 =0;
    				this.CompanyFundBC3 =0;
    				this.FundSubtotalBC3 =0;
    				this.Remark3 = String.Empty;
    				this.IsDelete =false;
    				this.VersionNo =0;
    				this.CreatedBy = String.Empty;
    				this.CreatedTime = DateTime.Now;
    				this.LastUpdatedBy = String.Empty;
    				this.LastUpdatedTime = DateTime.Now;
    				this.CompanyFund1 =0;
    		
    
    
    	}
    	    public string SalaryDetailsID { get; set; }
        public string EmpID { get; set; }
        public int SalaryMonth { get; set; }
        public string CustomerID { get; set; }
        public Nullable<decimal> PayableSalary1 { get; set; }
        public Nullable<decimal> IndiPension1 { get; set; }
        public Nullable<decimal> IndiMedical1 { get; set; }
        public Nullable<decimal> IndiJobSecurity1 { get; set; }
        public Nullable<decimal> IndiSSTotal1 { get; set; }
        public Nullable<decimal> IndiFund1 { get; set; }
        public Nullable<decimal> Tax1 { get; set; }
        public Nullable<decimal> AnnualBonus1 { get; set; }
        public Nullable<decimal> AnnualBonusTax1 { get; set; }
        public Nullable<decimal> RealSalary1 { get; set; }
        public Nullable<decimal> CompanyPension1 { get; set; }
        public Nullable<decimal> CompanyMedical1 { get; set; }
        public Nullable<decimal> CompanyJobSecurity1 { get; set; }
        public Nullable<decimal> IndusInsurance1 { get; set; }
        public Nullable<decimal> BirthInsurance1 { get; set; }
        public Nullable<decimal> CompanySSTotal1 { get; set; }
        public string Remark1 { get; set; }
        public Nullable<decimal> PayableSalary2 { get; set; }
        public Nullable<decimal> TranSubsidies2 { get; set; }
        public Nullable<decimal> MealAllowance2 { get; set; }
        public Nullable<decimal> TravelAllowance2 { get; set; }
        public Nullable<decimal> BackPay2 { get; set; }
        public Nullable<decimal> PayableTotal2 { get; set; }
        public Nullable<decimal> IndiFund2 { get; set; }
        public Nullable<decimal> IndiSSTotal2 { get; set; }
        public Nullable<decimal> IndiPension2 { get; set; }
        public Nullable<decimal> IndiMedical2 { get; set; }
        public Nullable<decimal> IndiJobSecurity2 { get; set; }
        public Nullable<decimal> Other2 { get; set; }
        public Nullable<decimal> Tax2 { get; set; }
        public Nullable<decimal> TaxDeductions2 { get; set; }
        public Nullable<decimal> RealSalary2 { get; set; }
        public string PaymentMode2 { get; set; }
        public string Remark2 { get; set; }
        public Nullable<decimal> PayBaseBK3 { get; set; }
        public Nullable<decimal> PayBase3 { get; set; }
        public Nullable<decimal> CompanyPension3 { get; set; }
        public Nullable<decimal> CompanyMedical3 { get; set; }
        public Nullable<decimal> CompanyJobSecurity3 { get; set; }
        public Nullable<decimal> CompanyInjury3 { get; set; }
        public Nullable<decimal> CompanyBirth3 { get; set; }
        public Nullable<decimal> CompanySSTotal3 { get; set; }
        public Nullable<decimal> CompanyPensionBK3 { get; set; }
        public Nullable<decimal> CompanyMedicalBK3 { get; set; }
        public Nullable<decimal> CompanyJobSecurityBK3 { get; set; }
        public Nullable<decimal> IndusInsuranceBK3 { get; set; }
        public Nullable<decimal> BirthInsuranceBK3 { get; set; }
        public Nullable<decimal> CompanySSTotalBK3 { get; set; }
        public Nullable<decimal> IndiPension3 { get; set; }
        public Nullable<decimal> IndiMedical3 { get; set; }
        public Nullable<decimal> IndiJobSecurity3 { get; set; }
        public Nullable<decimal> IndiSubtotal3 { get; set; }
        public Nullable<decimal> IndiPensionBK3 { get; set; }
        public Nullable<decimal> IndiMedicalBK3 { get; set; }
        public Nullable<decimal> IndiJobSecurityBK3 { get; set; }
        public Nullable<decimal> IndiSubtotalBK3 { get; set; }
        public Nullable<decimal> Total3 { get; set; }
        public Nullable<int> SalaryMonthBK3 { get; set; }
        public Nullable<decimal> FundAccount3 { get; set; }
        public Nullable<decimal> IndiFund3 { get; set; }
        public Nullable<decimal> CompanyFund3 { get; set; }
        public Nullable<decimal> FundSubtotal3 { get; set; }
        public Nullable<decimal> PayAmount3 { get; set; }
        public Nullable<decimal> FundAccountBC3 { get; set; }
        public Nullable<decimal> IndiFundBC3 { get; set; }
        public Nullable<decimal> CompanyFundBC3 { get; set; }
        public Nullable<decimal> FundSubtotalBC3 { get; set; }
        public string Remark3 { get; set; }
        public bool IsDelete { get; set; }
        public int VersionNo { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
        public Nullable<decimal> CompanyFund1 { get; set; }
    }
}
