//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TP_SysPersonCustomer
    {
        public string SysPersonID { get; set; }
        public string CustomerID { get; set; }
        public bool IsDelete { get; set; }
        public int VersionNo { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string LastUpdatedBy { get; set; }
        public System.DateTime LastUpdatedTime { get; set; }
    }
}
